"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_controller import SprinklerController


class TestSprinklerController(unittest.TestCase):
    """SprinklerController unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerController(self):
        """Test SprinklerController"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerController()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
