"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_sensor import LightSensor


class TestLightSensor(unittest.TestCase):
    """LightSensor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightSensor(self):
        """Test LightSensor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightSensor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
