"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_controller import SprinklerController
globals()['SprinklerController'] = SprinklerController
from openapi_client.model.sprinkler_controller_list200_response import SprinklerControllerList200Response


class TestSprinklerControllerList200Response(unittest.TestCase):
    """SprinklerControllerList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerControllerList200Response(self):
        """Test SprinklerControllerList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerControllerList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
