"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.global_config import GlobalConfig
globals()['GlobalConfig'] = GlobalConfig
from openapi_client.model.global_config_list200_response import GlobalConfigList200Response


class TestGlobalConfigList200Response(unittest.TestCase):
    """GlobalConfigList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalConfigList200Response(self):
        """Test GlobalConfigList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GlobalConfigList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
