"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.light_api import LightApi  # noqa: E501


class TestLightApi(unittest.TestCase):
    """LightApi unit test stubs"""

    def setUp(self):
        self.api = LightApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_light_config_calendar_create(self):
        """Test case for light_config_calendar_create

        """
        pass

    def test_light_config_calendar_delete(self):
        """Test case for light_config_calendar_delete

        """
        pass

    def test_light_config_calendar_list(self):
        """Test case for light_config_calendar_list

        """
        pass

    def test_light_config_calendar_partial_update(self):
        """Test case for light_config_calendar_partial_update

        """
        pass

    def test_light_config_calendar_read(self):
        """Test case for light_config_calendar_read

        """
        pass

    def test_light_config_calendar_update(self):
        """Test case for light_config_calendar_update

        """
        pass

    def test_light_config_create(self):
        """Test case for light_config_create

        """
        pass

    def test_light_config_daily_create(self):
        """Test case for light_config_daily_create

        """
        pass

    def test_light_config_daily_delete(self):
        """Test case for light_config_daily_delete

        """
        pass

    def test_light_config_daily_list(self):
        """Test case for light_config_daily_list

        """
        pass

    def test_light_config_daily_partial_update(self):
        """Test case for light_config_daily_partial_update

        """
        pass

    def test_light_config_daily_read(self):
        """Test case for light_config_daily_read

        """
        pass

    def test_light_config_daily_update(self):
        """Test case for light_config_daily_update

        """
        pass

    def test_light_config_delete(self):
        """Test case for light_config_delete

        """
        pass

    def test_light_config_list(self):
        """Test case for light_config_list

        """
        pass

    def test_light_config_partial_update(self):
        """Test case for light_config_partial_update

        """
        pass

    def test_light_config_read(self):
        """Test case for light_config_read

        """
        pass

    def test_light_config_type_create(self):
        """Test case for light_config_type_create

        """
        pass

    def test_light_config_type_delete(self):
        """Test case for light_config_type_delete

        """
        pass

    def test_light_config_type_list(self):
        """Test case for light_config_type_list

        """
        pass

    def test_light_config_type_partial_update(self):
        """Test case for light_config_type_partial_update

        """
        pass

    def test_light_config_type_read(self):
        """Test case for light_config_type_read

        """
        pass

    def test_light_config_type_update(self):
        """Test case for light_config_type_update

        """
        pass

    def test_light_config_update(self):
        """Test case for light_config_update

        """
        pass

    def test_light_controller_force_create(self):
        """Test case for light_controller_force_create

        """
        pass

    def test_light_controller_force_delete(self):
        """Test case for light_controller_force_delete

        """
        pass

    def test_light_controller_force_list(self):
        """Test case for light_controller_force_list

        """
        pass

    def test_light_controller_force_partial_update(self):
        """Test case for light_controller_force_partial_update

        """
        pass

    def test_light_controller_force_read(self):
        """Test case for light_controller_force_read

        """
        pass

    def test_light_controller_force_update(self):
        """Test case for light_controller_force_update

        """
        pass

    def test_light_controller_list(self):
        """Test case for light_controller_list

        """
        pass

    def test_light_controller_read(self):
        """Test case for light_controller_read

        """
        pass

    def test_light_device_create(self):
        """Test case for light_device_create

        """
        pass

    def test_light_device_delete(self):
        """Test case for light_device_delete

        """
        pass

    def test_light_device_list(self):
        """Test case for light_device_list

        """
        pass

    def test_light_device_partial_update(self):
        """Test case for light_device_partial_update

        """
        pass

    def test_light_device_read(self):
        """Test case for light_device_read

        """
        pass

    def test_light_device_update(self):
        """Test case for light_device_update

        """
        pass

    def test_light_sensor_list(self):
        """Test case for light_sensor_list

        """
        pass

    def test_light_sensor_read(self):
        """Test case for light_sensor_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
