"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_configuration_type import LightConfigurationType
globals()['LightConfigurationType'] = LightConfigurationType
from openapi_client.model.light_config_type_list200_response import LightConfigTypeList200Response


class TestLightConfigTypeList200Response(unittest.TestCase):
    """LightConfigTypeList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightConfigTypeList200Response(self):
        """Test LightConfigTypeList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightConfigTypeList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
