"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.water_controller import WaterController
globals()['WaterController'] = WaterController
from openapi_client.model.water_controller_list200_response import WaterControllerList200Response


class TestWaterControllerList200Response(unittest.TestCase):
    """WaterControllerList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaterControllerList200Response(self):
        """Test WaterControllerList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WaterControllerList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
