"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_device import LightDevice


class TestLightDevice(unittest.TestCase):
    """LightDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightDevice(self):
        """Test LightDevice"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightDevice()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
