"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_sensor import SprinklerSensor
globals()['SprinklerSensor'] = SprinklerSensor
from openapi_client.model.sprinkler_sensor_list200_response import SprinklerSensorList200Response


class TestSprinklerSensorList200Response(unittest.TestCase):
    """SprinklerSensorList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerSensorList200Response(self):
        """Test SprinklerSensorList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerSensorList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
