"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_configuration_calendar_range import LightConfigurationCalendarRange


class TestLightConfigurationCalendarRange(unittest.TestCase):
    """LightConfigurationCalendarRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightConfigurationCalendarRange(self):
        """Test LightConfigurationCalendarRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightConfigurationCalendarRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
