"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.water_device import WaterDevice
globals()['WaterDevice'] = WaterDevice
from openapi_client.model.water_device_list200_response import WaterDeviceList200Response


class TestWaterDeviceList200Response(unittest.TestCase):
    """WaterDeviceList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaterDeviceList200Response(self):
        """Test WaterDeviceList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WaterDeviceList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
