"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_sensor import LightSensor
globals()['LightSensor'] = LightSensor
from openapi_client.model.light_sensor_list200_response import LightSensorList200Response


class TestLightSensorList200Response(unittest.TestCase):
    """LightSensorList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightSensorList200Response(self):
        """Test LightSensorList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightSensorList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
