"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.water_force_controller import WaterForceController
globals()['WaterForceController'] = WaterForceController
from openapi_client.model.water_controller_force_list200_response import WaterControllerForceList200Response


class TestWaterControllerForceList200Response(unittest.TestCase):
    """WaterControllerForceList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaterControllerForceList200Response(self):
        """Test WaterControllerForceList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WaterControllerForceList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
