"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_force_controller import LightForceController
globals()['LightForceController'] = LightForceController
from openapi_client.model.light_controller_force_list200_response import LightControllerForceList200Response


class TestLightControllerForceList200Response(unittest.TestCase):
    """LightControllerForceList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightControllerForceList200Response(self):
        """Test LightControllerForceList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightControllerForceList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
