"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_force_controller import SprinklerForceController
globals()['SprinklerForceController'] = SprinklerForceController
from openapi_client.model.sprinkler_controller_force_list200_response import SprinklerControllerForceList200Response


class TestSprinklerControllerForceList200Response(unittest.TestCase):
    """SprinklerControllerForceList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerControllerForceList200Response(self):
        """Test SprinklerControllerForceList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerControllerForceList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
