"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.global_api import GlobalApi  # noqa: E501


class TestGlobalApi(unittest.TestCase):
    """GlobalApi unit test stubs"""

    def setUp(self):
        self.api = GlobalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_global_config_create(self):
        """Test case for global_config_create

        """
        pass

    def test_global_config_delete(self):
        """Test case for global_config_delete

        """
        pass

    def test_global_config_list(self):
        """Test case for global_config_list

        """
        pass

    def test_global_config_partial_update(self):
        """Test case for global_config_partial_update

        """
        pass

    def test_global_config_read(self):
        """Test case for global_config_read

        """
        pass

    def test_global_config_update(self):
        """Test case for global_config_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
