"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.water_api import WaterApi  # noqa: E501


class TestWaterApi(unittest.TestCase):
    """WaterApi unit test stubs"""

    def setUp(self):
        self.api = WaterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_water_config_create(self):
        """Test case for water_config_create

        """
        pass

    def test_water_config_delete(self):
        """Test case for water_config_delete

        """
        pass

    def test_water_config_list(self):
        """Test case for water_config_list

        """
        pass

    def test_water_config_partial_update(self):
        """Test case for water_config_partial_update

        """
        pass

    def test_water_config_read(self):
        """Test case for water_config_read

        """
        pass

    def test_water_config_update(self):
        """Test case for water_config_update

        """
        pass

    def test_water_controller_force_create(self):
        """Test case for water_controller_force_create

        """
        pass

    def test_water_controller_force_delete(self):
        """Test case for water_controller_force_delete

        """
        pass

    def test_water_controller_force_list(self):
        """Test case for water_controller_force_list

        """
        pass

    def test_water_controller_force_partial_update(self):
        """Test case for water_controller_force_partial_update

        """
        pass

    def test_water_controller_force_read(self):
        """Test case for water_controller_force_read

        """
        pass

    def test_water_controller_force_update(self):
        """Test case for water_controller_force_update

        """
        pass

    def test_water_controller_list(self):
        """Test case for water_controller_list

        """
        pass

    def test_water_controller_read(self):
        """Test case for water_controller_read

        """
        pass

    def test_water_device_create(self):
        """Test case for water_device_create

        """
        pass

    def test_water_device_delete(self):
        """Test case for water_device_delete

        """
        pass

    def test_water_device_list(self):
        """Test case for water_device_list

        """
        pass

    def test_water_device_partial_update(self):
        """Test case for water_device_partial_update

        """
        pass

    def test_water_device_read(self):
        """Test case for water_device_read

        """
        pass

    def test_water_device_update(self):
        """Test case for water_device_update

        """
        pass

    def test_water_sensor_list(self):
        """Test case for water_sensor_list

        """
        pass

    def test_water_sensor_read(self):
        """Test case for water_sensor_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
