"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_device import SprinklerDevice
globals()['SprinklerDevice'] = SprinklerDevice
from openapi_client.model.sprinkler_device_list200_response import SprinklerDeviceList200Response


class TestSprinklerDeviceList200Response(unittest.TestCase):
    """SprinklerDeviceList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerDeviceList200Response(self):
        """Test SprinklerDeviceList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerDeviceList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
