"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_configuration_daily_time_range import LightConfigurationDailyTimeRange
globals()['LightConfigurationDailyTimeRange'] = LightConfigurationDailyTimeRange
from openapi_client.model.light_config_daily_list200_response import LightConfigDailyList200Response


class TestLightConfigDailyList200Response(unittest.TestCase):
    """LightConfigDailyList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightConfigDailyList200Response(self):
        """Test LightConfigDailyList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightConfigDailyList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
