"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_controller import LightController


class TestLightController(unittest.TestCase):
    """LightController unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightController(self):
        """Test LightController"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightController()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
