"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_configuration import SprinklerConfiguration
globals()['SprinklerConfiguration'] = SprinklerConfiguration
from openapi_client.model.sprinkler_config_list200_response import SprinklerConfigList200Response


class TestSprinklerConfigList200Response(unittest.TestCase):
    """SprinklerConfigList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerConfigList200Response(self):
        """Test SprinklerConfigList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerConfigList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
