"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.sprinkler_force_controller import SprinklerForceController


class TestSprinklerForceController(unittest.TestCase):
    """SprinklerForceController unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSprinklerForceController(self):
        """Test SprinklerForceController"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SprinklerForceController()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
