"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.water_sensor import WaterSensor
globals()['WaterSensor'] = WaterSensor
from openapi_client.model.water_sensor_list200_response import WaterSensorList200Response


class TestWaterSensorList200Response(unittest.TestCase):
    """WaterSensorList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWaterSensorList200Response(self):
        """Test WaterSensorList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WaterSensorList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
