"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_force_controller import LightForceController


class TestLightForceController(unittest.TestCase):
    """LightForceController unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightForceController(self):
        """Test LightForceController"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightForceController()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
