"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_configuration_calendar_range import LightConfigurationCalendarRange
globals()['LightConfigurationCalendarRange'] = LightConfigurationCalendarRange
from openapi_client.model.light_config_calendar_list200_response import LightConfigCalendarList200Response


class TestLightConfigCalendarList200Response(unittest.TestCase):
    """LightConfigCalendarList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightConfigCalendarList200Response(self):
        """Test LightConfigCalendarList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightConfigCalendarList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
