"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_device import LightDevice
globals()['LightDevice'] = LightDevice
from openapi_client.model.light_device_list200_response import LightDeviceList200Response


class TestLightDeviceList200Response(unittest.TestCase):
    """LightDeviceList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightDeviceList200Response(self):
        """Test LightDeviceList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightDeviceList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
