"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.light_configuration import LightConfiguration
globals()['LightConfiguration'] = LightConfiguration
from openapi_client.model.light_config_list200_response import LightConfigList200Response


class TestLightConfigList200Response(unittest.TestCase):
    """LightConfigList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLightConfigList200Response(self):
        """Test LightConfigList200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LightConfigList200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
