"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

setup(
    name=NAME,
    version=VERSION,
    description="One-Green Core API Gateway ",
    author="OpenAPI Generator community",
    author_email="shanmugathas.vigneswaran@outlook.fr",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "One-Green Core API Gateway "],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Creative Commons Zero v1.0 Universal",
    long_description="""\
    Plant cultivation framework  # noqa: E501
    """
)
