# flake8: noqa

"""
    One-Green Core API Gateway 

    Plant cultivation framework  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: shanmugathas.vigneswaran@outlook.fr
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from og_client.api_client import ApiClient

# import Configuration
from og_client.configuration import Configuration

# import exceptions
from og_client.exceptions import OpenApiException
from og_client.exceptions import ApiAttributeError
from og_client.exceptions import ApiTypeError
from og_client.exceptions import ApiValueError
from og_client.exceptions import ApiKeyError
from og_client.exceptions import ApiException
